### ISSUE TITLE
Unable to decrypt the config backup

### ISSUE THREAD

**Issue by amlamarra** [Spearfoot/FreeNAS-scripts#10]
I used the `save_config_enc.sh` script to create an encrypted back. Then I used the example openssl command to try to decrypt it. However, I just get an error:

```
root@freenas ~/FreeNAS-scripts # ./save_config_enc.sh 
Backup configuration database file: /mnt/storage/backup/freenas/freenas-FreeNAS-11.3-RELEASE-c0e049a7fa-20200207121125.db
Configuration file copied with status 0

root@freenas ~ # openssl enc -d -aes256 -pass file:config_passphrase -in /mnt/storage/backup/freenas/freenas-FreeNAS-11.3-RELEASE-c0e049a7fa-20200207121125.db -out decrypted.db
bad magic number
```

**Comment by Spearfoot** [comment]
You passed the wrong filename as the input file. Specify the encrypted file as the input. It should have a '.enc' extension. On one of my systems, it is named:

bacon-FreeNAS-11.3-RELEASE ... .tar.gz.enc

Pass this '.enc' file as the input. You can use any name you like for the output, but it should end with '.tar.gz' so you can then open it as a tarball and extract the config file.

Here's an example:

openssl enc -d -aes256 -pass file:config_passphrase -in {}.tar.gz.enc -out {}.tar.gz

**Comment by amlamarra** [comment]
Sorry, I misunderstood the script. I thought the backup to the dataset was tarballed and encrypted. I didn't realize that it only does that when sending it as an email attachment.
