### ISSUE TITLE
smartctl requires /dev/{drive}

### ISSUE THREAD

**Issue by githubarooski** [Spearfoot/FreeNAS-scripts#12]
Hello, thanks for the work on this. The HDD temps doesn't work on my system (11.2-U7) due to smartctl requiring /dev/ in front of the drive ID

```
$ sudo smartctl -A da1
smartctl 6.6 2017-11-05 r4594 [FreeBSD 11.2-STABLE amd64] (local build)
Copyright (C) 2002-17, Bruce Allen, Christian Franke, www.smartmontools.org

da1: Unable to detect device type
Please specify device type with the -d option.
```

```
$ sudo smartctl -A /dev/da1 | grep Temp
194 Temperature_Celsius     0x0022   119   098   000    Old_age   Always       -       33

```

**Comment by githubarooski** [comment]
fixed mine by just adding it up top, in case it helps

```
# 1. A string constant; just key in the devices you want to report on here:
drives="/dev/da0 /dev/da1 /dev/da2 /dev/da3 /dev/da4 /dev/da5 /dev/da6 /dev/da7"
```

**Comment by Spearfoot** [comment]
Good point -- my example enumeration doesn't include the /dev/ specifier. 

I suggest using the 'get_smart_drives()' function, which does include the drive's full device specifier. This is what I always use.

I will update example enumeration in the script to include the /dev/ spec for the sake of users who prefer this approach.

Thanks!
