### ISSUE TITLE
date in zpool_report.sh after upgrade to TrueNAS CORE

### ISSUE THREAD

**Issue by michaelschefczyk** [Spearfoot/FreeNAS-scripts#14]
After upgrading to TrueNAS CORE, the zpool_report.sh script does return:

date: illegal option -- 0
usage: date [-jnRu] [-d dst] [-r seconds|file] [-t west] [-v[+|-]val[ymwdHMS]]
[-I[date | hours | minutes | seconds]]
[-f fmt date | [[[[[cc]yy]mm]dd]HH]MM[.ss]] [+format]
date: illegal option -- 2
usage: date [-jnRu] [-d dst] [-r seconds|file] [-t west] [-v[+|-]val[ymwdHMS]]
[-I[date | hours | minutes | seconds]]
[-f fmt date | [[[[[cc]yy]mm]dd]HH]MM[.ss]] [+format]

This will probably be connected to the OS upgrade and the scrubdate handling, but I do not understand the details.

Thank you  very much for your great scripts!! The only issue I am missing at large - not only here - is handling of NVMe devices in smart reports.

**Comment by Spearfoot** [comment]
You're very welcome! Glad you've found these scripts useful.

Thanks for the feedback. Now that TrueNAS has been released, I will install it on a VM and see about fixing this issue.

**Comment by Spearfoot** [comment]
I've submitted an update for compatibility with TrueNAS 12.0
