### ISSUE TITLE
3ware controller

### ISSUE THREAD

**Issue by tuplink** [Spearfoot/FreeNAS-scripts#3]
so for anyone who happens to stumble on this it wont work with a 3ware controller
solution
everyline that has smartctl .... /dev/$drive add twa0 -d 3ware,    after dev
 the line will read .../dev/twa0 -d 3ware,${drive}
then uncomment all of the 3 methods for determining drives and replace with drives="0 1 2 3 4 5 ....."

**Comment by Spearfoot** [comment]
Thanks for pointing this out. I've modified the readme page to include information about modifying the script to support different controllers.
