### ISSUE TITLE
email not working

### ISSUE THREAD

**Issue by NasKar2** [Spearfoot/FreeNAS-scripts#9]
smart_report.sh no longer sending email after upgrade to 11.3. I can send a test email from the GUI

**Comment by Spearfoot** [comment]
See this post on the FreeNAS forum, it explains how to modify the script to send mail under version 11.3:

https://www.ixsystems.com/community/threads/scripts-to-report-smart-zpool-and-ups-status-hdd-cpu-t%C2%B0-hdd-identification-and-backup-the-config.27365/page-40#post-567844

**Comment by Spearfoot** [comment]
I've investigated the new behavior of sendmail on FreeNAS 11.3-RELEASE and submitted a ticket to iXsystems. I will see how they respond and proceed accordingly.

**Comment by Spearfoot** [comment]
I modified the SMART and zpool report scripts to work with FreeNAS 11.3-RELEASE

**Comment by amlamarra** [comment]
I think you'll need to modify the ups_report.sh script as well.
